export * from './consent.gql-query';
export * from './quiz.gql-query';
export * from './warmup.gql-query';
export * from './qna.gql-query';
export * from './personalized.gql-query';
export * from './cloudinary.gql-query';
export * from './widen.gql-query';
export * from './fragments';
export * from './apollo';
